branch-defaults:
  master:
    environment: env-dev1
environment-defaults:
  env-dev1:
    branch: null
    repository: null
global:
  application_name: docker-cicd
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
