version: 2.1
orbs:
    awsebcli: sbc-orbs/awsebcli@0.0.3
jobs:
    test:
        docker:
            - image: circleci/node:9.2.0
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Testing
                command: docker-compose -f docker-compose-test.yml run docker-cicd
    deploy:
        docker:
            - image: circleci/node:9.2.0
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install EB Command Line
                command: >
                    sudo apt-get update &&
                    sudo apt-get upgrade &&
                    sudo docker pull python:3.6 &&
                    sudo apt-get install -y python3-dev python3-pip python3-virtualenv &&
                    sudo pip3 install awsebcli &&
                    sudo pip3 install --upgrade --user awsebcli
            - deploy:
                name: Deploy to AWS EB
                command: sudo eb deploy docker-cicd-dev
workflows:
    version: 2
    docker-cicd:
        jobs:
            - test
            - deploy:
                requires:
                    - test