version: 2
jobs:
    test:
        docker:
            - image: circleci/node:9.2.0
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Testing
                command: docker-compose -f docker-compose-test.yml run docker-cicd
    deploy:
        docker:
            - image: circleci/node:9.2.0
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install EB Command Line
                command: |
                    sudo apt-get -y -qq update &&
                    sudo apt-get install python-pip python-dev build-essential &&
                    sudo pip install --upgrade setuptools
                    sudo pip install awsebcli --upgrade
            - deploy:
                name: Deploy to AWS EB
                command: sudo eb deploy docker-cicd-dev
workflows:
    version: 2
    docker-cicd:
        jobs:
            - test
            - deploy:
                requires:
                    - test